version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - infra

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - infra

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    ports:
      - '4369:4369'
      - '5671:5671'
      - '15672:15672'
      - '25672:25672'
      - '${RABBITMQ_PORT}:5672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - infra

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server
    restart: always
    env_file:
      - .env
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - infra

  minio:
    restart: always
    container_name: minio
    image: docker.io/bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - .env
    volumes:
      - 'minio:/data'
    networks:
      - infra

networks:
  infra:
    name: 'infra'
    driver: bridge

volumes:
  minio:
    name: minio
    driver: local
  redis:
    name: redis
  postgres:
    name: postgres
  mysql:
    name: mysql
  rabbitmq:
    name: rabbitmq
  redis-config:
    name: redis-config
