name: Pull and build
on: [push, workflow_dispatch]
jobs:
  deploy:
    name: 'Deploy'
    runs-on:
      labels: self-hosted
      group: Default
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Run'
        run: |
          rm -rf .env || true
          cp .env.production .env
          docker compose up -d --build --force-recreate
